# This workflow to automatically build and deploy Sphinx documentation to GitHub Pages
# Triggers on push to main branch
# Steps:
    # 1. Checkout repository
    # 2. Setup Python environment
    # 3. Install Sphinx and project dependencies
    # 4. Build HTML documentation
    # 5. Redirect index to api.html
    # 6. Deploy to GitHub Pages branch
    # 7. Cleanup build artifacts

    name: Deploy Sphinx Documentation

    on:
      push:
        branches:
          - main
          - refactor/document_automation
      workflow_dispatch:

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.8'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install sphinx
              pip install .

          - name: Build documentation
            run: |
              cd docs
              make html

          - name: Redirect index to api.html
            run: |
              echo '<meta http-equiv="refresh" content="0; url=api.html" />' > docs/_build/html/index.html

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./docs/_build
              publish_branch: gh-pages
              force_orphan: true

          - name: Cleanup build files
            run: |
              rm -rf docs/_build/