# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create Test Data Directories
        run: |
          mkdir -p tests/_data/semantic_segmentation
          mkdir -p tests/_data/object_detection
          
      - name: Set up Test Data
        run: |
          echo '{"0": "background", "1": "necrotic_core", "2": "edema", "3": "enhancing"}' > tests/_data/semantic_segmentation/test_class_mappings.json
          echo '{"0": "red blood cell", "1": "trophozoite", "2": "schizont", "3": "difficult", "4": "ring", "5": "leukocyte"}' > tests/_data/object_detection/test_class_mappings.json

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/ -v